global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: services
    static_configs:
      - targets:
          - student-1:8000
          - student-2:8000
          - payment-1:8000
          - payment-2:8000
          - records-1:8000
          - records-2:8000
          - timetable-1:8000
          - timetable-2:8000
    relabel_configs:
      - source_labels: [__address__]
        regex: "([^:]+):.*"
        target_label: instance

  - job_name: haproxy
    static_configs:
      - targets: [gateway:8405]

  - job_name: patroni
    static_configs:
      - targets: [pg-1:8008, pg-2:8008]
    relabel_configs:
      - source_labels: [__address__]
        regex: "([^:]+):.*"
        target_label: instance
