"""Initial schema: one PostgreSQL schema per service.

Revision ID: 0001
Revises:
Create Date: 2026-09-29 11:56:27.225412
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SCHEMAS = ("student", "payment", "records", "timetable")


def upgrade() -> None:
    for schema in SCHEMAS:
        op.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courses")),
        sa.UniqueConstraint("code", name=op.f("uq_courses_code")),
        schema="student",
    )
    op.create_table(
        "students",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_no", sa.String(length=16), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("program", sa.String(length=80), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_students")),
        sa.UniqueConstraint("student_no", name=op.f("uq_students_student_no")),
        schema="student",
    )
    op.create_table(
        "sections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("term", sa.String(length=16), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("enrolled", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"], ["student.courses.id"], name=op.f("fk_sections_course_id_courses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sections")),
        schema="student",
    )
    op.create_index(
        op.f("ix_sections_course_id"), "sections", ["course_id"], unique=False, schema="student"
    )
    op.create_index(op.f("ix_sections_term"), "sections", ["term"], unique=False, schema="student")
    op.create_table(
        "registrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["student.sections.id"],
            name=op.f("fk_registrations_section_id_sections"),
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.students.id"],
            name=op.f("fk_registrations_student_id_students"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_registrations")),
        sa.UniqueConstraint(
            "student_id", "section_id", name=op.f("uq_registrations_student_id_section_id")
        ),
        schema="student",
    )
    op.create_index(
        op.f("ix_registrations_section_id"),
        "registrations",
        ["section_id"],
        unique=False,
        schema="student",
    )
    op.create_index(
        op.f("ix_registrations_student_id"),
        "registrations",
        ["student_id"],
        unique=False,
        schema="student",
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("term", sa.String(length=16), nullable=False),
        sa.Column("amount_due", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "opening_paid", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "amount_paid", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
        sa.UniqueConstraint("student_id", "term", name=op.f("uq_invoices_student_id_term")),
        schema="payment",
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("term", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("bank_charge_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        schema="payment",
    )
    op.create_index(
        op.f("ix_payments_student_id"), "payments", ["student_id"], unique=False, schema="payment"
    )
    op.create_table(
        "grades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("course_code", sa.String(length=16), nullable=False),
        sa.Column("term", sa.String(length=16), nullable=False),
        sa.Column("letter", sa.String(length=2), nullable=False),
        sa.Column("points", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grades")),
        sa.UniqueConstraint(
            "student_id", "course_code", "term", name=op.f("uq_grades_student_id_course_code_term")
        ),
        schema="records",
    )
    op.create_table(
        "transcript_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("gpa", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcript_documents")),
        schema="records",
    )
    op.create_index(
        op.f("ix_transcript_documents_student_id"),
        "transcript_documents",
        ["student_id"],
        unique=False,
        schema="records",
    )
    op.create_table(
        "generation_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("term", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("sections_total", sa.Integer(), server_default="0", nullable=False),
        sa.Column("sections_done", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_jobs")),
        schema="timetable",
    )
    op.create_index(
        op.f("ix_generation_jobs_term"),
        "generation_jobs",
        ["term"],
        unique=False,
        schema="timetable",
    )
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rooms")),
        sa.UniqueConstraint("code", name=op.f("uq_rooms_code")),
        schema="timetable",
    )
    op.create_table(
        "timeslots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("day", sa.String(length=3), nullable=False),
        sa.Column("starts_at", sa.String(length=5), nullable=False),
        sa.Column("ends_at", sa.String(length=5), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_timeslots")),
        schema="timetable",
    )
    op.create_table(
        "entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("term", sa.String(length=16), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("timeslot_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["room_id"], ["timetable.rooms.id"], name=op.f("fk_entries_room_id_rooms")
        ),
        sa.ForeignKeyConstraint(
            ["timeslot_id"],
            ["timetable.timeslots.id"],
            name=op.f("fk_entries_timeslot_id_timeslots"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entries")),
        sa.UniqueConstraint(
            "term", "room_id", "timeslot_id", name=op.f("uq_entries_term_room_id_timeslot_id")
        ),
        sa.UniqueConstraint("term", "section_id", name=op.f("uq_entries_term_section_id")),
        schema="timetable",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entries", schema="timetable")
    op.drop_table("timeslots", schema="timetable")
    op.drop_table("rooms", schema="timetable")
    op.drop_index(op.f("ix_generation_jobs_term"), table_name="generation_jobs", schema="timetable")
    op.drop_table("generation_jobs", schema="timetable")
    op.drop_index(
        op.f("ix_transcript_documents_student_id"),
        table_name="transcript_documents",
        schema="records",
    )
    op.drop_table("transcript_documents", schema="records")
    op.drop_table("grades", schema="records")
    op.drop_index(op.f("ix_payments_student_id"), table_name="payments", schema="payment")
    op.drop_table("payments", schema="payment")
    op.drop_table("invoices", schema="payment")
    op.drop_index(op.f("ix_registrations_student_id"), table_name="registrations", schema="student")
    op.drop_index(op.f("ix_registrations_section_id"), table_name="registrations", schema="student")
    op.drop_table("registrations", schema="student")
    op.drop_index(op.f("ix_sections_term"), table_name="sections", schema="student")
    op.drop_index(op.f("ix_sections_course_id"), table_name="sections", schema="student")
    op.drop_table("sections", schema="student")
    op.drop_table("students", schema="student")
    op.drop_table("courses", schema="student")
    # ### end Alembic commands ###
    for schema in SCHEMAS:
        op.execute(f"DROP SCHEMA IF EXISTS {schema}")
