"""Fault-tolerance columns: payment idempotency key and journal index, registration status
index, checkpoint and lease of timetable generation jobs.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 10:41:20.300437
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments",
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        schema="payment",
    )
    op.create_index(
        op.f("ix_payments_status_updated_at"),
        "payments",
        ["status", "updated_at"],
        unique=False,
        schema="payment",
    )
    op.create_unique_constraint(
        op.f("uq_payments_idempotency_key"), "payments", ["idempotency_key"], schema="payment"
    )
    op.create_index(
        op.f("ix_registrations_status"), "registrations", ["status"], unique=False, schema="student"
    )
    op.add_column(
        "generation_jobs",
        sa.Column("checkpoint", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        schema="timetable",
    )
    op.add_column(
        "generation_jobs",
        sa.Column("lease_owner", sa.String(length=64), nullable=True),
        schema="timetable",
    )
    op.add_column(
        "generation_jobs",
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        schema="timetable",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generation_jobs", "lease_until", schema="timetable")
    op.drop_column("generation_jobs", "lease_owner", schema="timetable")
    op.drop_column("generation_jobs", "checkpoint", schema="timetable")
    op.drop_index(op.f("ix_registrations_status"), table_name="registrations", schema="student")
    op.drop_constraint(
        op.f("uq_payments_idempotency_key"), "payments", schema="payment", type_="unique"
    )
    op.drop_index(op.f("ix_payments_status_updated_at"), table_name="payments", schema="payment")
    op.drop_column("payments", "idempotency_key", schema="payment")
    # ### end Alembic commands ###
